<?xml version="2.0"?>
<!DOCTYPE root [
<!ELEMENT root (student, student, student)>
<!ELEMENT student (mark+)>
<!ELEMENT mark (#PCDATA)>
<!ATTLIST mark discipline CDATA #REQUIRED>
<!ATTLIST student name CDATA #REQUIRED>
]>
<root>
  <student name="Stepan">
    <mark discipline="English">5</mark>
    <mark discipline="Russian">4</mark>
  </student>
  <student name="Denis">
    <mark discipline="English">5</mark>
  </student>
  <student name="Julia">
    <mark discipline="INTR">3</mark>
  </student>
</root>
